Hi @zlatko-minev,

Upon running some initial tests, it does not seem like the `pyside6-port` branch is ready to be merged... Below is a brief report summarizing the issues observed during the testing process:

## Environment

- **System:** macOS 15.1  
- **Python Version:** 3.10.6 (via Conda environment with Anaconda3 as the manager)  
- **Setup:** Tested in a fresh Conda environment using the `environment.yml` file in the PR branch.  
- **Tests:**  
  - Executed using `run_all_tests.py`  
  - Design workflow files used in our lab that work with the current `main` branch  

---


## Issues

**tldr;**

[Explain the issues and link to the txt file for the entire error log]

